stages:
    - mavenbuild
    - maventest
    - autodeploy
    - androidbuild
    - androidtest
maven-build:
    stage: mavenbuild
    tags:
        - shell
    script:
        - cd Backend/ExpensesTracked_backend 
        - mvn package -B
maven-test:
    stage: maventest
    tags:
        - shell
    script:
        - cd Backend/ExpensesTracked_backend
        - mvn test
    artifacts:
            paths:
                - Backend/ExpensesTracked_backend/target/*.jar
autodeploy:
    stage: autodeploy
    tags:
        - shell
    script:
        - cd Backend/ExpensesTracked_backend
        - mvn package
        - sudo mv target/*.jar /target/expensestracked-demo.jar
        - sudo systemctl stop system-expensestracked-demo
        - sudo systemctl start system-expensestracked-demo
        
android-build:
    image: javiersantos/android-ci:latest
    stage: androidbuild
    before_script:
        - export GRADLE_USER_HOME=`pwd`/.gradle
        - chmod +x ./Frontend/AndroidLogin/gradlew
    tags:
        - frontend
    script:
        - cd Frontend/AndroidLogin
        - ./gradlew assemble
    artifacts:
        paths:
        - Frontend/AndroidLogin/app/build/outputs/
        
unitTests: 
    image: javiersantos/android-ci:latest
    stage: androidtest
    before_script:
        - export GRADLE_USER_HOME=`pwd`/.gradle
        - chmod +x ./Frontend/AndroidLogin/gradlew
    tags:
        - frontend
    script:
        - cd Frontend/AndroidLogin
        - ./gradlew test
