stages:
    - mavenbuild
    - maventest
    - autodeploy
maven-build:
    stage: mavenbuild
    tags:
        - shell
    script:
        - cd Backend/ExpensesTracked_backend 
        - mvn package -B
maven-test:
    stage: maventest
    tags:
        - shell
    script:
        - cd Backend/ExpensesTracked_backend
        - mvn test
    artifacts:
            paths:
                - Backend/ExpensesTracked_backend/target/*.jar
autodeploy:
    stage: autodeploy
    tags:
        - shell
    script:
        - cd Backend/ExpensesTracked_backend
        - mvn package
        - sudo mv target/*.jar /target/expensestracked-demo.jar
        - sudo systemctl stop system-expensestracked-demo
        - sudo systemctl start system-expensestracked-demo
